package sarc_reglas.nacimiento;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Nacimiento implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Nacimiento() {
    }

	/**Globales*/
	
	public final static String STRING_RESPUESTA_DROOLS = "NO_HAY_RESPUESTA_DE_DROOLS";
		
	/**Valores de comparacion*/
	
	public final static String CASO_MADRE_Y_PADRE_PRESENTES               			  = "MADRE_Y_PADRE_PRESENTES";
	public final static String CASO_MADRE_Y_PADRE_PRESENTES_AMBOS_CON_ID  			  = "MADRE_Y_PADRE_PRESENTES_AMBOS_CON_ID";
	public final static String CASO_MADRE_Y_PADRE_PRESENTES_AMBOS_SIN_ID  			  = "MADRE_Y_PADRE_PRESENTES_AMBOS_SIN_ID";
	public final static String CASO_MADRE_Y_PADRE_PRESENTES_ALGUNO_SIN_ID 			  = "MADRE_Y_PADRE_PRESENTES_ALGUNO_SIN_ID";
	public final static String CASO_MADRE_Y_PADRE_PRESENTES_PADRE_SIN_ID 			  = "MADRE_Y_PADRE_PRESENTES_PADRE_SIN_ID";
	public final static String CASO_MADRE_Y_PADRE_PRESENTES_MADRE_SIN_ID 			  = "MADRE_Y_PADRE_PRESENTES_MADRE_SIN_ID";
	public final static String CASO_MADRE_Y_PADRE_PRESENTES_AMBOS_SIN_ID_MADRE_CON_DJ = "MADRE_Y_PADRE_PRESENTES_AMBOS_SIN_ID_MADRE_CON_DJ";
	public final static String CASO_MADRE_Y_PADRE_PRESENTES_AMBOS_SIN_ID_MADRE_SIN_DJ = "MADRE_Y_PADRE_PRESENTES_AMBOS_SIN_ID_MADRE_SIN_DJ";

	
	public final static String CASO_MADRE_O_PADRE_PRESENTE        			= "CASO_MADRE_O_PADRE_PRESENTE";
	public final static String CASO_MADRE_O_PADRE_PRESENTE_CON_ID 			= "CASO_MADRE_O_PADRE_PRESENTE_CON_ID";
	public final static String CASO_MADRE_O_PADRE_PRESENTE_SIN_ID 			= "CASO_MADRE_O_PADRE_PRESENTE_SIN_ID";
	public final static String CASO_MADRE_O_PADRE_PRESENTE_PADRE_SIN_ID 	= "CASO_MADRE_O_PADRE_PRESENTE_PADRE_SIN_ID";
	public final static String CASO_MADRE_O_PADRE_PRESENTE_MADRE_SIN_ID 	= "CASO_MADRE_O_PADRE_PRESENTE_MADRE_SIN_ID";
	
	public final static String CASO_MADRE_Y_PADRE_NO_PRESENTES 				= "CASO_MADRE_Y_PADRE_NO_PRESENTES";
		
	/**Acciones de redireccion*/
	
	// Madre y Padre Presentes
    public final static String  ACCION_VISTA_MADRE_Y_PADRE_PRESENTES                    		= "madre_y_padre_presentes_vista";
	
	public final static String  ACCION_VISTA_MADRE_Y_PADRE_PRESENTES_AMBOS_CON_ID       		= "madre_y_padre_presentes_ambos_con_id_vista";
	public final static String  ACCION_VISTA_MADRE_Y_PADRE_PRESENTES_AUTENTICAR_4       		= "madre_y_padre_presentes_autenticar_4_vista";
	
	public final static String  ACCION_VISTA_MADRE_Y_PADRE_PRESENTES_AMBOS_SIN_ID       		= "madre_y_padre_presentes_ambos_sin_id_vista";
	public final static String  ACCION_VISTA_MADRE_Y_PADRE_PRESENTES_AMBOS_SIN_ID_AUTENTICAR_6  = "madre_y_padre_presentes_ambos_sin_id_autenticar_6_vista";
	public final static String  ACCION_VISTA_MADRE_Y_PADRE_PRESENTES_AMBOS_SIN_ID_AUTENTICAR_4  = "madre_y_padre_presentes_ambos_sin_id_autenticar_4_vista";
	public final static String  ACCION_VISTA_MADRE_Y_PADRE_PRESENTES_AMBOS_SIN_ID_AUTENTICAR_2  = "madre_y_padre_presentes_ambos_sin_id_autenticar_2_vista";
		
	public final static String  ACCION_VISTA_MADRE_Y_PADRE_PRESENTES_ALGUNO_SIN_ID 				= "madre_y_padre_presentes_alguno_sin_id_vista";	
	public final static String  ACCION_VISTA_PADRE_SIN_ID										= "padre_sin_id_vista";
	public final static String  ACCION_VISTA_MADRE_SIN_ID										= "madre_sin_id_vista";	
	public final static String  ACCION_VISTA_PADRE_SIN_ID_AUTENTICAR_5 							= "padre_sin_id_autenticar_5_vista";
	public final static String  ACCION_VISTA_PADRE_SIN_ID_AUTENTICAR_3 							= "padre_sin_id_autenticar_3_vista";	
	public final static String  ACCION_VISTA_MADRE_SIN_ID_AUTENTICAR_5 							= "madre_sin_id_autenticar_5_vista";
	public final static String  ACCION_VISTA_MADRE_SIN_ID_AUTENTICAR_3 							= "madre_sin_id_autenticar_3_vista";	
	
	// Madre o Padre Presente	
    public final static String  ACCION_VISTA_MADRE_PRESENTE                             = "madre_presente_vista";
    public final static String  ACCION_VISTA_PADRE_PRESENTE                             = "padre_presente_vista";
	
	public final static String  ACCION_VISTA_MADRE_PRESENTE_CON_ID_AUTENTICAR_3         = "madre_presente_con_id_autenticar_3_vista";
	public final static String  ACCION_VISTA_PADRE_PRESENTE_CON_ID_AUTENTICAR_3         = "padre_presente_con_id_autenticar_3_vista";
	
	public final static String  ACCION_VISTA_MADRE_PRESENTE_SIN_ID                      = "madre_presente_sin_id_vista";
	public final static String  ACCION_VISTA_PADRE_PRESENTE_SIN_ID                      = "padre_presente_sin_id_vista";
	public final static String  ACCION_VISTA_MADRE_PRESENTE_SIN_ID_AUTENTICAR_5         = "madre_presente_sin_id_autenticar_5_vista";
	public final static String  ACCION_VISTA_MADRE_PRESENTE_SIN_ID_AUTENTICAR_3         = "madre_presente_sin_id_autenticar_3_vista";
	public final static String  ACCION_VISTA_PADRE_PRESENTE_SIN_ID_AUTENTICAR_5         = "padre_presente_sin_id_autenticar_5_vista";
	public final static String  ACCION_VISTA_PADRE_PRESENTE_SIN_ID_AUTENTICAR_3         = "padre_presente_sin_id_autenticar_3_vista";

	//Madre y Padre No Presentes
	public final static String  ACCION_VISTA_MADRE_Y_PADRE_NO_PRESENTES_AUTENTICAR_3    = "madre_padre_no_presentes_autenticar_3_vista";
        
	/**Acciones de respuesta*/
	
	private Boolean  continuarEvaluando = true;
	
	private String 	 accion;
	private String	 escenario;	
	private String 	 tipoRegistro;
	private String 	 casoTramite;

	private Boolean  estaMadrePresente;
	private Boolean  estaPadrePresente;
	private Boolean  estaMadreYPadrePresentes;	
	private Boolean  estaMadreConID;
	private Boolean  estaPadreConID;
	private Boolean  estaRepresentanteConID;	
	private Boolean  estaMadreConDJ;
	private Boolean  estaPadreConDJ;	
	private Boolean  estaTestigo1Presente;
	private Boolean  estaTestigo2Presente;
	
	private int      cantParticipantes;
	
	public Boolean getContinuarEvaluando() {
		return continuarEvaluando;
	}
	
	public void setContinuarEvaluando(Boolean continuarEvaluando) {
		this.continuarEvaluando = continuarEvaluando;
	}
	
	public String getAccion() {
		return accion;
	}
	
	public void setAccion(String accion) {
		this.accion = accion;
	}
	
	public String getEscenario() {
		return escenario;
	}
	
	public void setEscenario(String escenario) {
		this.escenario = escenario;
	}
	
	public String getTipoRegistro() {
		return tipoRegistro;
	}
	
	public void setTipoRegistro(String tipoRegistro) {
		this.tipoRegistro = tipoRegistro;
	}
	
	public String getCasoTramite() {
		return casoTramite;
	}
	
	public void setCasoTramite(String casoTramite) {
		this.casoTramite = casoTramite;
	}
	
	public Boolean getEstaMadrePresente() {
		return estaMadrePresente;
	}
	
	public void setEstaMadrePresente(Boolean estaMadrePresente) {
		this.estaMadrePresente = estaMadrePresente;
	}
	
	public Boolean getEstaPadrePresente() {
		return estaPadrePresente;
	}
	
	public void setEstaPadrePresente(Boolean estaPadrePresente) {
		this.estaPadrePresente = estaPadrePresente;
	}
	
	public Boolean getEstaMadreYPadrePresentes() {
		return estaMadreYPadrePresentes;
	}
	
	public void setEstaMadreYPadrePresentes(Boolean estaMadreYPadrePresentes) {
		this.estaMadreYPadrePresentes = estaMadreYPadrePresentes;
	}
	
	public Boolean getEstaMadreConID() {
		return estaMadreConID;
	}
	
	public void setEstaMadreConID(Boolean estaMadreConID) {
		this.estaMadreConID = estaMadreConID;
	}
	
	public Boolean getEstaPadreConID() {
		return estaPadreConID;
	}
	
	public void setEstaPadreConID(Boolean estaPadreConID) {
		this.estaPadreConID = estaPadreConID;
	}
	
	public Boolean getEstaRepresentanteConID() {
		return estaRepresentanteConID;
	}
	
	public void setEstaRepresentanteConID(Boolean estaRepresentanteConID) {
		this.estaRepresentanteConID = estaRepresentanteConID;
	}
	
	public Boolean getEstaMadreConDJ() {
		return estaMadreConDJ;
	}
	
	public void setEstaMadreConDJ(Boolean estaMadreConDJ) {
		this.estaMadreConDJ = estaMadreConDJ;
	}
	
	public Boolean getEstaPadreConDJ() {
		return estaPadreConDJ;
	}
	
	public void setEstaPadreConDJ(Boolean estaPadreConDJ) {
		this.estaPadreConDJ = estaPadreConDJ;
	}
	
	public Boolean getEstaTestigo1Presente() {
		return estaTestigo1Presente;
	}
	
	public void setEstaTestigo1Presente(Boolean estaTestigo1Presente) {
		this.estaTestigo1Presente = estaTestigo1Presente;
	}
	
	public Boolean getEstaTestigo2Presente() {
		return estaTestigo2Presente;
	}
	
	public void setEstaTestigo2Presente(Boolean estaTestigo2Presente) {
		this.estaTestigo2Presente = estaTestigo2Presente;
	}
	
	public int getCantParticipantes() {
		return cantParticipantes;
	}

	public void setCantParticipantes(int cantParticipantes) {
		this.cantParticipantes = cantParticipantes;
	}

}